### ISSUE TITLE
[Docker] Upload Docker Images for Reproducing MLSys'21 Artifact to DockerHub

### ISSUE THREAD

**Issue by wangshangsam** [UofT-EcoSystem/hfta#24]
Just in case if people don't wanna rebuild those images again.

**Comment by wangshangsam** [comment]
[native1.6-cu10.2](https://hub.docker.com/layers/wangshangsam/hfta/mlsys21_native1.6-cu10.2/images/sha256-a505f9f15df7f667ee6cd1f83ea543a861b6e88333e4936eedb10c09426f7c0f?context=explore):
```bash
docker pull wangshangsam/hfta:mlsys21_native1.6-cu10.2
```

**Comment by wangshangsam** [comment]
[nvidia20.06](https://hub.docker.com/layers/wangshangsam/hfta/mlsys21_nvidia20.06/images/sha256-7fbe8cd90568c3c901180f8f36bec27eb88b1a5e455c2a505d932810b418c3f6?context=explore)
```bash
docker pull wangshangsam/hfta:mlsys21_nvidia20.06
```

**Comment by wangshangsam** [comment]
@nixli @ypm1999 I'm wondering if you could help to check if those two images work, then update `docs/mlsys21/a100_throughputs.md` and `docs/mlsys21/v100_rtx6000_throughputs.md` accordinly (just say something like "if you don't want to build the image manually, you can pull our pre-built image by xxx")?

**Comment by nixli** [comment]
I am checking rtx6000, if you have not checked a100 yet, I can do that as well :)

**Comment by ypm1999** [comment]
I am checking A100, it works well up now

**Comment by nixli** [comment]
same for RTX6000, I'll update the README

**Comment by wangshangsam** [comment]
@ypm1999 I don't see `docker pull wangshangsam/hfta:mlsys21_native1.6-cu10.2` being mentioned in #27 . 

@nixli I'm wondering if you could update https://github.com/UofT-EcoSystem/hfta/blob/main/docs/mlsys21/a100_throughputs.md#build-docker-image as well?

**Comment by nixli** [comment]
added in #34
