### ISSUE TITLE
[Docs] `Nsight Compute` -> `Nsight System` in docs/mlsys21/a100_throughputs.md

### ISSUE THREAD

**Issue by wangshangsam** [UofT-EcoSystem/hfta#29]
`nsys_cli_2020.3.1.72.deb` is actually Nsight System CLI, not Nsight Compute CLI. (Thus, the link to the download website should probably be updated too).

In https://github.com/UofT-EcoSystem/hfta/blob/main/docs/mlsys21/a100_throughputs.md#acquiring-nvidia-nsight-compute-cli-and-dcgm .

**Comment by nixli** [comment]
fixed in #34
