### ISSUE TITLE
[Docs] Only `nvidia20.06` version docker image should be built for A100

### ISSUE THREAD

**Issue by wangshangsam** [UofT-EcoSystem/hfta#30]
In https://github.com/UofT-EcoSystem/hfta/blob/main/docs/mlsys21/a100_throughputs.md#build-docker-image . A100 doesn't support CUDA < 11.0, thus `native1.6-cu10.2` would not work. `nvidia20.08` could work too, but we were mostly using `nvidia20.06` for our experiments.

**Comment by nixli** [comment]
Done as part of PR #34
